name: Update data.json

on:
  schedule:
    - cron: '*/5 * * * *' # TODO update this to twice a day or so

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14'

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install deps
        run: npm install

      - name: Install deps
        run: npm run update

      - name: Update data.json on GitHub
        uses: test-room-7/action-update-file@v1.5.0
        with:
          file-path: data.json
          commit-msg: AUTOMATIC data.json UPDATE COMMIT
          github-token: ${{ secrets.GITHUB_TOKEN }}
